### ISSUE TITLE
Error in mPointStart

### ISSUE THREAD

**Issue by rashenoy** [pkleczko/CustomGauge#1]
mPointSize is using a.getColor(R.styleable.CustomGauge_pointSize,0) instead of a.getInt(R.styleable.CustomGauge_pointSize,0)  because of which it was giving errors. Should it be getColor or getInt ?

**Comment by pkleczko** [comment]
As I remember getColor is correct. Can you copy+paste this error?

Pawel

Pozdrawiam, Best regards,

Paweł Kleczkowski  |  _Freelancer - Mobile Developer_

mobile  +48 669 934 133
email  contact@pawelkleczkowski.pl  emil@netmart.pl
skype  pkleczko

Rozwiązania Informatyczne dla Biznesu - Paweł Kleczkowski
03-556 Warszawa, ul. Handlowa 34/17
www.pawelkleczkowski.pl

2015-06-23 10:23 GMT+02:00 Ravi Shenoy notifications@github.com:

**Comment by rashenoy** [comment]
Why should it be getColor() ? The pointSize in xml is setting the point size, an int and the parser is just setting to mPointSize. Color is set separately, isnt it ?

**Comment by pkleczko** [comment]
Oh, yes, it's mPointSize (size). You're probably right. In fact I
remembered this code had worked for me, but maybe I made some changes and
didn't verify them. If it works for you with getInt it's a bug.

Pozdrawiam, Best regards,

Paweł Kleczkowski  |  _Freelancer - Mobile Developer_

mobile  +48 669 934 133
email  contact@pawelkleczkowski.pl  emil@netmart.pl
skype  pkleczko

Rozwiązania Informatyczne dla Biznesu - Paweł Kleczkowski
03-556 Warszawa, ul. Handlowa 34/17
www.pawelkleczkowski.pl

2015-06-23 11:46 GMT+02:00 Ravi Shenoy notifications@github.com:

**Comment by rashenoy** [comment]
Thanks for the response. getColor will also work, because getColor also takes Int and returns Int. But it might return a size (some enum corresponding to the input value) it might NOT be the size that app wants.
