### ISSUE TITLE
Cannot set Endvalue Programmatically

### ISSUE THREAD

**Issue by anandasir073311** [pkleczko/CustomGauge#10]
If i am setting Endvalue programmatically then its not redrawing the Gauge. After i made the setvalue() method like this it worked.

```
public void setEndValue(int endValue) {
    mEndValue = endValue;
    mPointAngle = ((double) Math.abs(mSweepAngle) / (mEndValue - mStartValue));
    invalidate();
}
```

Is there any other solution for this?

**Comment by pkleczko** [comment]
Hi,

Yes, after you change settings like endValue or startValue you have to invalidate view. Not sure if that should be in each setter, but it can be good idea. I will consider it.

**Comment by EzequielMessore** [comment]
Will this ever be fixed?

**Comment by pkleczko** [comment]
sory, I no longer support this library. but feel welcome to contribute and add this functionality
