### ISSUE TITLE
Gauge at center of view

### ISSUE THREAD

**Issue by jacobozamora** [pkleczko/CustomGauge#11]
Hi!

I saw some problems with the component when I adjust weight and height as match_parent, because the gauge isn't at center of the view and some parts it's out of bound.

I've make some changes in the code to solve it. 

I would like to prove this changes and upload them.

The file has been uploaded as .txt

[CustomGauge.txt](https://github.com/pkleczko/CustomGauge/files/552969/CustomGauge.txt)

Best regads,

Juan Antonio.

**Comment by pkleczko** [comment]
Hi,

Thanks for feedback Juan. I will add your fixes in next version.

**Comment by jacobozamora** [comment]
You're welcome!

I would be happy if you put me as collaborator :dancer: 

Best regards,

**Comment by pkleczko** [comment]
I think that you have to make pull request to become contributor?

**Comment by jacobozamora** [comment]
Maybe, I'll go to see it :+1:

**Comment by jacobozamora** [comment]
I just finished the pull request :)
