### ISSUE TITLE
can i make gauge 3 as flat

### ISSUE THREAD

**Issue by nzala** [pkleczko/CustomGauge#13]
[https://github.com/pkleczko/CustomGauge/blob/master/example.png](url)

i mean like LED- or LCD-like bar gauge control for iOS
[https://github.com/ChiefPilot/F3BarGauge](url)

**Comment by pkleczko** [comment]
You mean vertical or horizontal one? This Gauge doesn't have such functionallity.

**Comment by nzala** [comment]
hw can i achieve it any idea

**Comment by pkleczko** [comment]
Add couple of rectangle views and change their color depending on percentage value.
