### ISSUE TITLE
Possible to add scale and dividers?

### ISSUE THREAD

**Issue by Sharan25** [pkleczko/CustomGauge#3]
Trying to utilize this gauge in developing a speedometer, I would want to define the scale and add dividers after every 10 values. Could you help me with it?

**Comment by Sharan25** [comment]
Also, Cannot select colors for start point and end point even though I have defined gauge:pointStartColor = "@color/Green" the gauge starts with blue (as it is defined in the java code).  
And mPointColor is not shown in the gauge.

**Comment by pkleczko** [comment]
Hi @Sharan25,

You motivated me to refresh lib - thanks. I migrated it to gradle, so now it's much easier to import it.

And I added logic for dividers. Not very pretty, but it can inspire you to expand it. Is this what you needed?

As you can see in example pointStartColor works correctly. Don't know why it didn't work for you - can you send me your code (can be private message). I think gradients doesn't work very well, hope one day I will verify it, but in general pointStartColor should works correctly.

**Comment by Sharan25** [comment]
Hey, @pkleczko 
Thank you for responding. I had just imported your library into studio and ran a the Example to see how it works. Did not change the code. 
Thank for adding the dividers logic. Appreciate the effort.

**Comment by Sharan25** [comment]
Hey, @pkleczko I am trying to generate the reading numbers exactly at the point where the divider is drawn and I have not able to complete it. Can you help me with it?

**Comment by pkleczko** [comment]
Hej,

You should modify library and add drawText method in required points
(similar to dividers logic)

Hope I helped

Pozdrawiam, Best regards,

Paweł Kleczkowski

mobile  +48 669 934 133
email  contact@pawelkleczkowski.pl  emil@netmart.pl
skype  @pkleczko

Rozwiązania Informatyczne dla Biznesu - Paweł Kleczkowski
03-556 Warszawa, ul. Handlowa 34/17
www.pawelkleczkowski.pl

2016-02-22 6:41 GMT+01:00 Sharan25 notifications@github.com:
