### ISSUE TITLE
Progress above divider

### ISSUE THREAD

**Issue by candeiasdan** [pkleczko/CustomGauge#4]
How to paint the progress above dividers?

If i have 50% of progress i would like to see the 50% of full color and 50% of dividers.

**Comment by pkleczko** [comment]
Just copy CustomGauge class (https://github.com/pkleczko/CustomGauge/blob/master/CustomGauge/src/main/java/pl/pawelkleczkowski/customgauge/CustomGauge.java) into your project and change order in onDraw method. I think that if you move dividers block (lines 149-157) before block with progress draw (lines 132-147) then progress will be up to dividers as you expected.

Let me know if this helped

**Comment by candeiasdan** [comment]
Perfect! Thanks.
