### ISSUE TITLE
add endValue value by code.

### ISSUE THREAD

**Issue by moonandroid** [pkleczko/CustomGauge#6]
How we can add end value programmatically ?

**Comment by pkleczko** [comment]
Hi,

No such feature in current version. I will add it in the future. You can just copy this class to your project and add method setEndValue.
https://github.com/pkleczko/CustomGauge/blob/master/CustomGauge/src/main/java/pl/pawelkleczkowski/customgauge/CustomGauge.java

**Comment by moonandroid** [comment]
Ok.

**Comment by moonandroid** [comment]
Hello
I have some issue when uses this class.
My max length is 150 and i got result 50 out of 150.

So i can display this result in Gauge class.
which attributes values need to change.

   app:gaugeStartAngel="180"
                app:gaugeSweepAngel="180"
                app:gaugeStrokeCap="BUTT"
                app:gaugeStrokeWidth="10dp"
                app:gaugeStartValue="0"
                app:gaugePointSize="0"
                app:gaugeEndValue="180"

**Comment by pkleczko** [comment]
Setters and getters added in v.1.0.3

**Comment by moonandroid** [comment]
Ok
I'll check
thanks
